# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

install: pip install tox

script: tox

notifications:
  email: false

# 2016-11-19: From cookiecutter:
#  python: 3.5
#  script: tox -e $TOXENV
#  after_success:
#      # Report coverage results to codecov.io
#      - pip install codecov
#      - codecov

